@startuml

title __QUERIES's Class Diagram__\n

  namespace orders {
    namespace controller.queries {
      class orders.controller.queries.ArtOrderController {
          {static} - connection : Connection
          {static} - resultSet : ResultSet
          {static} - statement : Statement
          {static} + accept()
          {static} + acceptedOrders()
          {static} + apply()
          {static} + changeImage()
          {static} + completedOrders()
          {static} + drawnOrders()
          {static} + finish()
          {static} + getByCustomer()
          {static} + inOrders()
          {static} + outOrders()
          {static} + processOrders()
          {static} + remove()
      }
    }
  }
  

  namespace orders {
    namespace controller.queries {
      class orders.controller.queries.GalleryController {
          {static} - connection : Connection
          {static} - resultSet : ResultSet
          {static} - statement : Statement
          {static} + addGallery()
          {static} + getGalleries()
          {static} + remove()
      }
    }
  }
  

  namespace orders {
    namespace controller.queries {
      class orders.controller.queries.OrderApplicationController {
          {static} - connection : Connection
          {static} - resultSet : ResultSet
          {static} - statement : Statement
          {static} + formQuery()
          {static} + getAll()
          {static} + getByID()
          {static} + placeOrder()
      }
    }
  }
  

  namespace orders {
    namespace controller.queries {
      class orders.controller.queries.UserController {
          {static} - connection : Connection
          {static} - resultSet : ResultSet
          {static} - statement : Statement
          {static} + changePassword()
          {static} + editProfile()
          {static} + getAll()
          {static} + getByID()
          {static} + login()
          {static} + register()
          {static} + setAvatar()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
